id: P006881
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS60403
  title: གསུང་ཐོར་བུ་། ཟླ་གསལ་དབང་མོ
  author: ''
  volumes:
    88a52571e3a24dda99803f6e9e33547d:
      image_group_id: I1GS60405
      title: ''
      volume_number: 1
      total_pages: 314
