id: I0F3FA120
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T08:03:40+00:00'
last_modified: '2022-06-08T07:32:37.004326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS60403
  title: གསུང་ཐོར་བུ་། ཟླ་གསལ་དབང་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A17A:
      image_group_id: I1GS60405
      title: ''
      total_pages: 314
      order: 1
      base_file: A17A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
